DROP DATABASE IF EXISTS SchoolDB;
CREATE DATABASE SchoolDB;
USE SchoolDB;
CREATE TABLE LEARNERS (
    StudentID INT PRIMARY KEY,
    FirstName VARCHAR(50),
    LastName VARCHAR(50),
    Gender VARCHAR(10),
    Course VARCHAR(50)
);
INSERT INTO LEARNERS
VALUES (1, 'John', 'Kamau', 'Male', 'DBMS');
SELECT * FROM LEARNERS;
USE SchoolDB;
SELECT * FROM LEARNERS;
INSERT INTO LEARNERS
VALUES (3, 'Peter', 'Otieno', 'Male', 'Information Technology');
SELECT * FROM LEARNERS;
UPDATE LEARNERS
SET Course = 'Computer Science'
WHERE StudentID = 1;
DELETE FROM LEARNERS
WHERE StudentID = 3;
SELECT COUNT(*) AS TotalStudents
FROM LEARNERS;
SELECT * FROM LEARNERS;
INSERT INTO LEARNERS
VALUES (2, 'Mary', 'Akinyi', 'Female', 'Computer Science');
SELECT * FROM LEARNERS;
INSERT INTO LEARNERS
VALUES (3, 'Peter', 'Otieno', 'Male', 'Information Technology');
INSERT INTO LEARNERS
VALUES (3, 'Peter', 'Otieno', 'Male', 'Information Technology');
INSERT INTO LEARNERS
VALUES (4, 'Grace', 'Wanjiku', 'Female', 'Business Management');
SELECT * FROM LEARNERS;
INSERT INTO LEARNERS
VALUES (3, 'Peter', 'Otieno', 'Male', 'Information Technology');
SELECT * FROM LEARNERS;
UPDATE LEARNERS
SET Course = 'Software Engineering'
WHERE StudentID = 1;
SELECT * FROM LEARNERS;
SELECT * 
FROM LEARNERS
WHERE Gender = 'Female';
SELECT * FROM LEARNERS;
DELETE FROM LEARNERS
WHERE StudentID = 3;
SELECT * FROM LEARNERS;
SELECT * 
FROM LEARNERS
WHERE Gender = 'Female';
SELECT COUNT(*) AS TotalStudents
FROM LEARNERS;
SELECT *
FROM LEARNERS
ORDER BY FirstName;
SELECT *
FROM LEARNERS
WHERE Course = 'Computer Science';
SELECT *
FROM LEARNERS
WHERE Gender = 'Male';
SELECT Gender, COUNT(*) AS Total
FROM LEARNERS
GROUP BY Gender;
SELECT Gender, COUNT(*) AS Total
FROM LEARNERS
GROUP BY Gender;
SELECT FirstName, LastName
FROM LEARNERS;
ALTER TABLE LEARNERS
ADD Email VARCHAR(100);
DESCRIBE LEARNERS;
UPDATE LEARNERS
SET Email = 'john@gmail.com'
WHERE StudentID = 1;
SELECT * FROM LEARNERS;
DESCRIBE LEARNERS;
ALTER TABLE LEARNERS
ADD Email VARCHAR(100);
ALTER TABLE LEARNERS
ADD Email VARCHAR(100);
DESCRIBE LEARNERS;
DESCRIBE LEARNERS;
ALTER TABLE LEARNERS
ADD Email VARCHAR(100);
DESCRIBE LEARNERS;
SELECT * FROM LEARNERS;
USE SchoolDB;
SHOW TABLES;
SELECT * FROM LEARNERS;
CREATE VIEW StudentView AS
SELECT FirstName, LastName, Course
SELECT * FROM StudentView;
